project/recipes/forms.py
# project/recipes/forms.py

from flask_wtf import Form
from wtforms import StringField
from wtforms.validators import DataRequired


class AddRecipeForm(Form):
    recipe_title = StringField('Recipe Title', validators=[DataRequired()])
    recipe_description = StringField('Recipe Description', validators=[DataRequired()])

project/recipes/views.py
# project/recipes/views.py

###############
#### imports ####
###############

from flask import render_template, Blueprint, request, redirect, url_for, flash
from project import db
from project.models import Recipe
from .forms import AddRecipeForm

##############
#### config ####
##############

recipes_blueprint = Blueprint('recipes', __name__)

##########################
#### helper functions ####
##########################

def flash_errors(form):
    for field, errors in form.errors.items():
        for error in errors:
            flash(u"Error in the %s field - %s" % (
                getattr(form, field).label.text,
                error
            ), 'info')


##############
#### routes ####
##############

@recipes_blueprint.route('/')
def index():
    all_recipes = Recipe.query.all()
    return render_template('recipes.html', recipes = all_recipes )

@recipes_blueprint.route('/add', methods=['GET','POST'])
def add_recipe():
    form = AddRecipeForm(request.form)
    if request.method == 'POST':
        if form.validate_on_submit():
            new_recipe = Recipe(form.recipe_title.data, form.recipe_description.data)
            db.session.add(new_recipe)
            db.session.commit()
            flash('New recipe, {}, added!'.format(new_recipe.recipe_title), 'success')
            return redirect(url_for('recipes.index'))
        else:
            flash_errors(form)
            flash('ERROR! Recipe was not added.','error')
    return render_template('add_recipe.html', form=form)

project/users/views.py
# project/users/views.py

###############
#### imports ####
###############

from flask import render_template, Blueprint, request, redirect, url_for, flash
from sqlalchemy.exc import IntegrityError
from flask_login import login_user, current_user, login_required, logout_user
from flask_mail import Message
from threading import Thread
from itsdangerous import URLSafeTimedSerializer
from datetime import datetime


from .forms import RegisterForm, LoginForm
from project import db, mail, app
from project.models import User

##############
#### config ####
##############

users_blueprint = Blueprint('users', __name__)

##########################
#### helper functions ####
##########################


def flash_errors(form):
    for field, errors in form.errors.items():
        for error in errors:
            flash(u"Error in the %s field - %s" % (
                getattr(form, field).label.text,
                error
            ), 'info')


def send_async_email(msg):
    with app.app_context():
        mail.send(msg)


def send_email(subject, recipients, html_body):
    msg = Message(subject, recipients=recipients)
    msg.html = html_body
    thr = Thread(target=send_async_email, args=[msg])
    thr.start()


def send_confirmation_email(user_email):
    confirm_serializer = URLSafeTimedSerializer(app.config['SECRET_KEY'])

    confirm_url = url_for(
        'users.confirm_email',
        token=confirm_serializer.dumps(
            user_email, salt='email-confirmation-salt'),
        _external=True)

    html = render_template(
        'email_confirmation.html',
        confirm_url=confirm_url)

    send_email('Confirm Your Email Address', [user_email], html)


################
#### routes ####
################


@users_blueprint.route('/register', methods=['GET', 'POST'])
def register():
    form = RegisterForm(request.form)
    if request.method == 'POST':
        if form.validate_on_submit():
            try:
                new_user = User(form.email.data, form.password.data)
                new_user.authenticated = True
                db.session.add(new_user)
                db.session.commit()

                send_confirmation_email(new_user.email)
                flash(
                    'Thanks for registering!  Please check your email to confirm your email address.', 'success')
                return redirect(url_for('recipes.index'))
            except IntegrityError:
                db.session.rollback()
                flash('ERROR! Email ({}) already exists.'.format(
                    form.email.data), 'error')
    return render_template('register.html', form=form)


@users_blueprint.route('/login', methods=['GET', 'POST'])
def login():
    form = LoginForm(request.form)
    if request.method == 'POST':
        if form.validate_on_submit():
            user = User.query.filter_by(email=form.email.data).first()
            if user is not None and user.is_correct_password(form.password.data):
                user.authenticated = True
                db.session.add(user)
                db.session.commit()
                login_user(user)
                flash('Thanks for logging in, {}'.format(current_user.email))
                return redirect(url_for('recipes.index'))
            else:
                flash('ERROR! Incorrect login credentials.', 'error')
    return render_template('login.html', form=form)


@users_blueprint.route('/logout')
@login_required
def logout():
    user = current_user
    user.authenticated = False
    db.session.add(user)
    db.session.commit()
    logout_user()
    flash('Goodbye!', 'info')
    return redirect(url_for('users.login'))


@users_blueprint.route('/confirm/<token>')
def confirm_email(token):
    try:
        confirm_serializer = URLSafeTimedSerializer(app.config['SECRET_KEY'])
        email = confirm_serializer.loads(
            token, salt='email-confirmation-salt', max_age=3600)
    except:
        flash('The confirmation link is invalid or has expired.', 'error')
        return redirect(url_for('users.login'))

    user = User.query.filter_by(email=email).first()

    if user.email_confirmed:
        flash('Account already confirmed. Please login.', 'info')
    else:
        user.email_confirmed = True
        user.email_confirmed_on = datetime.now()
        db.session.add(user)
        db.session.commit()
        flash('Thank you for confirming your email address!','success')

    return redirect(url_for('recipes.index'))

project/templates/_form_macros.html
{% macro render_field(field) %}

<dt>{{ field.label }}:</dt>

<dd>{{ field(**kwargs)|safe }}
    {% if field.errors %}
    <span class="error">
        {% for error in field.errors %}
            {{ error }}
        {% endfor %}
    </span>
    {% endif %}
</dd>

{% endmacro %}

project/templates/add_recipe.html
{% extends "layout.html" %}
{% from "_form_macros.html" import render_field %}

{% block content %}

<div class="add-recipe">
    <div class="page-header">
        <h2>Add a New Recipe</h2>
    </div>

    <form action="{{ url_for('recipes.add_recipe') }}" method="post">
        <div class="row justify-content-center">
            <div class="col-md-6">
                {{ form.csrf_token }}
                <dl>
                    {{ render_field(form.recipe_title, class="form-control",  placeholder="Enter Recipe Title") }}
                    {{ render_field(form.recipe_description, class="form-control",  placeholder="Enter Recipe Description") }}
                </dl>
                <button class="btn btn-primary" type="submit">Add Recipe</button>
            </div>
        </div>
    </form>
</div>

{% endblock %}

project/templates/email_confirmation.html
{# project/templates/email_confirmation.html #}

Your account on Family Recipes was successfully created.
Please click the link below to confirm your email address and
activate your account:

<a href="{{ confirm_url }}">{{ confirm_url }}</a>

--
Questions? Comments? Email demg.inc.mx@gmail.com.

project/templates/layout.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Family Recipe App">
    <meta name="author" content="David Mendez Guardado">
    <title>Family Recipe App</title>
    <!-- styles -->
    <link rel="stylesheet" href="{{ url_for('static', filename='lib/bootstrap-4.4.1-dist/css/bootstrap.min.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/main.css') }}">
</head>

<body>

    <!-- Static navbar -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
        <div class="container">

            <!-- Brand and toggle get grouped for better mobile display -->
            <a class="navbar-brand" href="{{ url_for('recipes.index') }}">Family Recipes</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="nav navbar-nav mr-auto">
                    {% if current_user.is_authenticated %}
                        <li class="nav-item"><a class="nav-link" href="{{ url_for('recipes.index') }}">Public
                                Recipes</a></li>
                        <li class="nav-item"><a class="nav-link" href="{{ url_for('recipes.add_recipe') }}">Add
                                Recipe</a></li>
                        <li class="nav-item"><a class="nav-link" href="{{ url_for('users.logout') }}">Log Out</a></li>
                    {% else %}
                        <li class="nav-item"><a class="nav-link" href="{{ url_for('users.register') }}">Register</a>
                        </li>
                        <li class="nav-item"><a class="nav-link" href="{{ url_for('users.login') }}">Log In</a></li>
                    {% endif %}
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    {% if current_user.is_authenticated %}
                        <li class="nav-item"><a class="nav-link" href="#">Welcome, {{current_user.email}}!</a></li>
                    {% else %}
                        <li class="nav-item"><a class="nav-link" href="#">Welcome!</a></li>
                    {% endif %}

                </ul>
            </div>
            <!--/.nav-collapse -->
        </div><!-- /.container -->
    </nav>

    <div class="container">
        <div class="content">

            <!-- flash messages -->
            {% for error_message in get_flashed_messages(category_filter=["error"]) %}
            <div class="alert alert-danger alert-dismissible">{{ error_message }}</div>
            {% endfor %}
            {% for success_message in get_flashed_messages(category_filter=["success"]) %}
            <div class="alert alert-success alert-dismissible">{{ success_message }}</div>
            {% endfor %}
            {% for info_message in get_flashed_messages(category_filter=["info"]) %}
            <div class="alert alert-info alert-dismissible">{{ info_message }}</div>
            {% endfor %}

            <!-- child template -->
            {% block content %}
            {% endblock %}

        </div>
        <div class="footer">
            <hr>
            <p>&copy; LSCA David Mendez Guardado - 2020</p>
        </div>
    </div><!-- /.container -->

    <!-- scripts -->
    <script src="//code.jquery.com/jquery-1.11.3.min.js"></script>
    <script src="{{ url_for('static', filename='lib/bootstrap-4.4.1-dist/js/bootstrap.min.js') }}"></script>
</body>

</html>

project/templates/login.html
{% extends "layout.html" %}
{% from "_form_macros.html" import render_field %}

{% block content %}

<div class="user-registration">
    <div class="page-header">
        <h2>Log In</h2>
    </div>
    <form action="{{ url_for('users.login') }}" method="post">
        <div class="row justify-content-center">
            <div class="col-md-6">
                {{ form.csrf_token }}
                <dl>
                    {{ render_field(form.email, class="form-control", placeholder="Email address") }}
                    {{ render_field(form.password, class="form-control", placeholder="Password") }}
                </dl>
                <button class="btn btn-primary" type="submit">Log In</button>
                <em>Need an account? </em><a href="/register">Signup!!</a>
            </div>
        </div>
    </form>
</div>
{% endblock %}

project/templates/recipes.html
{% extends "layout.html" %}
{% block content %}
<div class="page-header">
    <h2>Recipes</h2>
</div>
<div class="row">
    <div class="col-md-12">
        <table class="table table-striped" id="owned_stock_table">
            <thead>
                <tr>
                    <td>Title</td>
                    <td>Description</td>
                </tr>
            </thead>
            <tbody>
                {% for recipe in recipes %}
                <tr>
                    <td>{{ recipe.recipe_title }}</td>
                    <td>{{ recipe.recipe_description }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>

{% endblock %}

project/templates/register.html
{% extends "layout.html" %}
{% from "_form_macros.html" import render_field %}

{% block content %}
<div class="user-registration">
    <div class="page-header">
        <h2>Please Register Your New Account</h2>
    </div>
    <form action="{{ url_for('users.register') }}" method="post">
        <div class="row justify-content-center">
            <div class="col-md-6">
                {{ form.csrf_token }}
                <dl>
                    {{ render_field(form.email, class="form-control",  placeholder="Email address") }}
                    {{ render_field(form.password, class="form-control",  placeholder="Password") }}
                    {{ render_field(form.confirm, class="form-control",  placeholder="Confirm password") }}
                </dl>
                <button class="btn btn-primary" type="submit">Create New Account</button>
            </div>
        </div>
    </form>
</div>

{% endblock %}